// ABOUTME: Use case for creating a new city with validation
// ABOUTME: Checks slug uniqueness and admin permissions before creation

import { CityRepository } from '../../ports/CityRepository'
import { IUserRepository } from '../../ports/repositories/IUserRepository'
import { City } from '../../../domain/entities/City'
import { CitySlug } from '../../../domain/value-objects/CitySlug'
import { UserId } from '../../../domain/value-objects/UserId'

export interface CreateCityRequest {
  adminUserId: string
  name: string
  slug: string
  imageUrl: string
  description?: string
  active?: boolean
  displayOrder?: number
}

export interface CreateCityResponse {
  success: boolean
  city?: City
  error?: string
}

/**
 * CreateCityUseCase
 *
 * Creates a new city with validation:
 * - Checks if user is admin
 * - Validates slug uniqueness
 * - Creates city entity
 */
export class CreateCityUseCase {
  constructor(
    private cityRepository: CityRepository,
    private userRepository: IUserRepository
  ) {}

  async execute(request: CreateCityRequest): Promise<CreateCityResponse> {
    // 1. Check admin permissions
    const adminUserId = UserId.create(request.adminUserId)
    if (!adminUserId) {
      return {
        success: false,
        error: 'Invalid user ID'
      }
    }

    const adminUser = await this.userRepository.findById(adminUserId)
    if (!adminUser || !adminUser.isAdmin()) {
      return {
        success: false,
        error: 'Unauthorized: Only admins can create cities'
      }
    }

    // 2. Validate slug format
    const citySlug = CitySlug.create(request.slug)
    if (!citySlug) {
      return {
        success: false,
        error: 'Invalid slug format'
      }
    }

    // 3. Check slug uniqueness
    const slugTaken = await this.cityRepository.slugExists(citySlug)
    if (slugTaken) {
      return {
        success: false,
        error: 'Slug already exists'
      }
    }

    // 4. Get next ID (for new city)
    // Note: In real implementation, this would be auto-generated by DB
    // For now, we'll let the DB handle it via SERIAL
    const city = City.createNew(
      0, // Will be replaced by DB auto-increment
      request.name,
      request.slug,
      request.imageUrl,
      {
        description: request.description,
        active: request.active ?? true,
        displayOrder: request.displayOrder ?? 0
      }
    )

    try {
      // 5. Create city
      const createdCity = await this.cityRepository.create(city)

      return {
        success: true,
        city: createdCity
      }
    } catch (error) {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to create city'
      }
    }
  }
}
